### ISSUE TITLE
Ingame crash

### ISSUE THREAD

**Issue by hdkhanh462** [ShadowyLycan990/ZenlessZoneZero-render-fix#1]
Thank for your app, i can go in game without crash now but when i going to this mission it will crash again T.T
![image](https://github.com/ShadowyLycan990/ZenlessZoneZero-render-fix/assets/101619460/a4cf9cd2-2164-4b57-b064-3af3a3eb0e21)

**Comment by Camillunita** [comment]
I have the same problem. The renderer isDirectX12
here is the player log when the crash ocurred
[Player.log](https://github.com/user-attachments/files/16100797/Player.log)

**Comment by ShadowyLycan990** [comment]
I can't help on that, sorry also this program is on end of life now because it's not working at all. The only solutions that is waiting for HoYo for fixing the game or Intel for pushing new driver for Intel UHD (iGPU) and other Intel GPUs.

As for the Legacy Intel HD there's no hope because it's been discontinued for so long and already superseded by Intel UHD since mid 6th Gen and Intel UHD will be discontinued sooner because it's already superseded by Intel Iris Plus & Arc & Iris Xe.

**Comment by ShadowyLycan990** [comment]
The new crash fix method is already founded, so now try to use the updated program!

**Comment by Camillunita** [comment]
thank u ♥️
Can I ask how do you manage to solve the problem? just for curiocity.

**Comment by ShadowyLycan990** [comment]
It's by some members of ZZZ Official Discord server, they founded out that their launcher dropped the update that fixed the crash but the other didn't get the updated file. Just that.
